GET /api/groups/1/posts?page=1&pageSize=10&sortBy=latest&keyword=tag1&isPublic=true
//게시글 목록 조회

###
PUT /api/posts/1
Content-Type: application/json
//게시글 수정 

###
DELETE /api/posts/1
Content-Type: application/json

//게시글 삭제 로직